services:
  web-client:
    build:
      context: ./client
      dockerfile: ./.docker/Dockerfile
    ports:
      - '4000:4000'

  server:
    build:
      context: ./server
      dockerfile: ./.docker/Dockerfile
    ports:
      - '8000:8000'
