apiVersion: v1
kind: Service
metadata:
  name: k-sockets-server-service
spec:
  selector:
    app: k-sockets-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000 # Match the containerPort specified in the Deployment YAML
  type: NodePort # Exposes the service on a random port on the host machine
